name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Decode keystore file
        uses: timheuer/base64-to-file@v1
        id: findroid_keystore
        with:
          fileName: "findroid-keystore.jks"
          encodedString: ${{ secrets.FINDROID_KEYSTORE }}

      - name: Set up Android SDK path
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Create keystore.properties
        run: |
          cat > keystore.properties <<EOF
          storeFile=${{ steps.findroid_keystore.outputs.filePath }}
          storePassword=${{ secrets.FINDROID_KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.FINDROID_KEY_ALIAS }}
          keyPassword=${{ secrets.FINDROID_KEY_PASSWORD }}
          EOF

      - name: Build
        run: ./gradlew clean app:phone:assembleLibreRelease

      - name: Rename apk files
        working-directory: ./app/phone/build/outputs/apk/libre/release/
        run: |
          for f in *.apk; do mv "$f" "${f/phone/findroid}"; done
          for f in *.apk; do mv "$f" "${f/-release/}"; done

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            ./app/phone/build/outputs/apk/libre/release/findroid-libre-arm64-v8a.apk
            ./app/phone/build/outputs/apk/libre/release/findroid-libre-armeabi-v7a.apk
            ./app/phone/build/outputs/apk/libre/release/findroid-libre-x86_64.apk
            ./app/phone/build/outputs/apk/libre/release/findroid-libre-x86.apk
